Repository SOPT-all/35-COLLABORATION-iOS-MARKETKURLY, pull requests merged in 2024-11, with the labels that each got.

#6 [refactor] #5 group -> forder
  MarketKurly.xcodeproj/project.pbxproj
  MarketKurly/Base.lproj/Main.storyboard
Labels: 기초 세팅

#7 Feature/ #3 home base ui (topNavigation, tabBar, scrollTab) implementation
  MarketKurly/Application/SceneDelegate.swift
  MarketKurly/Core/Extensions/NSAttributedString+.swift
  MarketKurly/Core/Extensions/UIStackView+.swift
  MarketKurly/Core/Extensions/UIView+.swift
  MarketKurly/Core/UI/Resources/Assets.xcassets/.DS_Store
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/icn_home_cart.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/icn_home_cart.imageset/icn_home_cart.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/icn_home_notification.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/icn_home_notification.imageset/icn_home_notification.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/img_home_logo.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/HomeTopNavigationIcons/img_home_logo.imageset/img_home_logo.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_category_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_category_activate.imageset/icn_home_category_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_category_default.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_category_default.imageset/icn_home_category_default.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_home_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_home_activate.imageset/icn_home_home_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_home_default.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_home_default.imageset/icn_home_home_default.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_lounge_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_lounge_activate.imageset/icn_home_lounge_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_lounge_default.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_lounge_default.imageset/icn_home_lounge_default.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_mykurly_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_mykurly_activate.imageset/icn_home_mykurly_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_mykurly_default.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_mykurly_default.imageset/icn_home_mykurly_default.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_search_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_search_activate.imageset/icn_home_search_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_search_default.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/TabBarIcons/icn_home_search_default.imageset/icn_home_search_default.svg
  MarketKurly/Presentation/Home/.gitkeep
  MarketKurly/Presentation/Home/View/ScrollTab/HomeScrollTab.swift
  MarketKurly/Presentation/Home/View/ScrollTab/HomeScrollTabCell.swift
  MarketKurly/Presentation/Home/View/TopNavigation/HomeSwitchTab.swift
  MarketKurly/Presentation/Home/View/TopNavigation/HomeSwitchTabState.swift
  MarketKurly/Presentation/Home/View/TopNavigation/HomeTopNavigation.swift
  MarketKurly/Presentation/Home/ViewControllers/HomeViewController.swift
  MarketKurly/Presentation/TabBar/ViewControllers/TabBarController.swift
  MarketKurly/Presentation/TabBar/ViewControllers/TabBarDummyViewControllers/CategoryViewController.swift
  MarketKurly/Presentation/TabBar/ViewControllers/TabBarDummyViewControllers/LoungeViewController.swift
  MarketKurly/Presentation/TabBar/ViewControllers/TabBarDummyViewControllers/MyPageViewController.swift
  MarketKurly/Presentation/TabBar/ViewControllers/TabBarDummyViewControllers/SearchViewController.swift
  MarketKurly/Presentation/TabBar/ViewControllers/TabBarPage.swift
Labels: UI 구현, 기초 세팅, 지석

#9 Feature/#2 review UI
  MarketKurly/Core/Extensions/UITableViewCell+.swift
  MarketKurly/Core/Extensions/UIView+.swift
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Black18.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/CoolGray1.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/CoolGray2.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/CoolGray3.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/CoolGray4.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/CoolGray5.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/GradientGray1.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray1.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray2.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray3.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray4.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray5.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray6.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray7.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Gray8.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Mint1.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Mint2.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Mint3.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Primary200.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Primary300.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Primary400.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Primary500.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Primary600.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Primary700.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/Red.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/White.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Font/MarketKurlyFont.swift
  MarketKurly/Data/API/.gitkeep
  MarketKurly/Data/Models/Request/.gitkeep
  MarketKurly/Data/Models/Response/.gitkeep
  MarketKurly/Presentation/Detail/.gitkeep
  MarketKurly/Presentation/Review/.gitkeep
  MarketKurly/Presentation/Review/Cell/ReviewTableViewCell.swift
  MarketKurly/Presentation/Review/Cell/ReviewTableViewHeader.swift
  MarketKurly/Presentation/Review/Cell/ReviewTableViewTitleSectionCell.swift
  MarketKurly/Presentation/Review/Model/ReviewData.swift
  MarketKurly/Presentation/Review/View/KurlyImageGridView.swift
  MarketKurly/Presentation/Review/View/RatingStarView.swift
  MarketKurly/Presentation/Review/ViewController/ReviewViewController.swift
  MarketKurly/Presentation/Wish/.gitkeep
Labels: UI 구현

#11 Fix/#2 modify unadded asset and color name
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/KurlyRed.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Color/KurlyWhite.colorset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_drop_down.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_drop_down.imageset/icn_review_down.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_star_filled.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_star_filled.imageset/icn_review_star_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_star_unfilled.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_star_unfilled.imageset/Star 14.svg
Labels: 상욱

#15 Feature/#14 detail view snackbar, connect review view
  MarketKurly.xcodeproj/project.pbxproj
  MarketKurly/Core/UI/Resources/Assets.xcassets/icn_save_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/icn_save_activate.imageset/icn_save_activate.svg
  MarketKurly/Core/UI/Resources/Font/MarketKurlyFont.swift
  MarketKurly/Presentation/Detail/Cell/RelatedGoodsCell.swift
  MarketKurly/Presentation/Detail/Model/Goods.swift
  MarketKurly/Presentation/Detail/View/GoodsInfo.swift
  MarketKurly/Presentation/Detail/View/PriceInfo.swift
  MarketKurly/Presentation/Detail/View/RelatedGoods.swift
  MarketKurly/Presentation/Detail/View/SellerInfo.swift
  MarketKurly/Presentation/Detail/ViewController/DetailViewController.swift
  MarketKurly/Presentation/Detail/ViewController/TempViewController.swift
  MarketKurly/Presentation/SegmentedControl/SegmentedPageViewController.swift
  MarketKurly/Presentation/SegmentedControl/UnderlineSegmentedControl.swift
Labels: UI 구현, 세민

#16 Feature/#10 wishlist UI
  MarketKurly/Core/Extensions/UICollectionViewCell+.swift
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_back_button.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_back_button.imageset/icn_arrow_left.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_cart_18.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_cart_18.imageset/icn_wishlisht_cart.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_cart_40.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_cart_40.imageset/icn_cart_large.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_notification.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Icons/ic_notification.imageset/icn_wishlist_notification.svg
  MarketKurly/Presentation/Home/View/ScrollTab/HomeScrollTabCell.swift
  MarketKurly/Presentation/Wish/Cell/WishListCategoryCollectionView.swift
  MarketKurly/Presentation/Wish/Cell/WishListCategoryCollectionViewCell.swift
  MarketKurly/Presentation/Wish/Cell/WishListTableViewCell.swift
  MarketKurly/Presentation/Wish/Model/WishListModel.swift
  MarketKurly/Presentation/Wish/ViewController/WishListViewController.swift
Labels: 상욱, UI 구현

#18 Feature/#17 detail view api
  MarketKurly/Core/Network/Detail/DetailApi.swift
  MarketKurly/Core/Network/Detail/DetailDTO.swift
  MarketKurly/Core/Network/Detail/DetailTarget.swift
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_description_info.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_description_info.imageset/icn_description_info.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_arrow_down.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_arrow_down.imageset/icn_goods_arrow_down.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_arrow_right.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_arrow_right.imageset/icn_goods_arrow_right.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_arrow_up.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_arrow_up.imageset/icn_goods_arrow_up.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_members.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_members.imageset/icn_goods_members.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_share.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/PriceInfo/icn_goods_share.imageset/icn_goods_share.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/icn_cart_small.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/icn_cart_small.imageset/icn_cart_small.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/icn_goods_nextgoods.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/icn_goods_nextgoods.imageset/icn_goods_nextgoods.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related1.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related1.imageset/related1.png
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related2.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related2.imageset/related2.png
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related3.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related3.imageset/related3.png
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related4.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/RelatedGoods/related4.imageset/related4.png
  MarketKurly/Core/UI/Resources/Assets.xcassets/Wish/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Wish/icn_save_activate.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Wish/icn_save_activate.imageset/icn_save_activate.svg
  MarketKurly/Core/UI/Resources/Assets.xcassets/Wish/icn_save_default.imageset/Contents.json
  MarketKurly/Core/UI/Resources/Assets.xcassets/Wish/icn_save_default.imageset/icn_save_default.svg
  MarketKurly/Presentation/Detail/Model/Goods.swift
  MarketKurly/Presentation/Detail/View/GoodsInfo.swift
  MarketKurly/Presentation/Detail/View/PriceInfo.swift
  MarketKurly/Presentation/Detail/View/SellerInfo.swift
  MarketKurly/Presentation/Detail/ViewController/DetailViewController.swift
Labels: 서버 연동, 세민

#21 Feature/#20 detail view wish api
  MarketKurly/Core/Network/NetworkManager.swift
  MarketKurly/Core/Network/Wish/WishApi.swift
  MarketKurly/Core/Network/Wish/WishDTO.swift
  MarketKurly/Core/Network/Wish/WishTarget.swift
  MarketKurly/Presentation/Detail/ViewController/DetailViewController.swift
Labels: 서버 연동, 세민

#23 Feature/#19 review wishlist api
  MarketKurly/Core/Network/NetworkManager.swift
  MarketKurly/Core/Network/Review/ResponseReviewDTO.swift
  MarketKurly/Core/Network/Review/ReviewApi.swift
  MarketKurly/Core/Network/Review/ReviewTarget.swift
  MarketKurly/Core/Network/TargetType.swift
  MarketKurly/Core/Network/WishList/ResponseWishListDTO.swift
  MarketKurly/Core/Network/WishList/WishListApi.swift
  MarketKurly/Core/Network/WishList/WishListTarget.swift
  MarketKurly/Presentation/Review/Cell/ReviewTableViewCell.swift
  MarketKurly/Presentation/Review/ViewController/ReviewViewController.swift
  MarketKurly/Presentation/Wish/Cell/WishListTableViewCell.swift
  MarketKurly/Presentation/Wish/ViewController/WishListViewController.swift
Labels: 서버 연동
